#page title
page_title                                : Beacon Mail                                         # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Beacon Mail                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free. Forever.                                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Email. Reinvented for the 21st Century.

enable_smart_app_banner                   : false                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Beacon Labs                                
your_link                                 : https://emilbaehr.com                     
your_city                                 : Oakville                                
email_address                             : beaconmailapp@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : beaconmailapp
github_username                           : beacon-labs
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Powerful Algorithmic Feed
    description                           : We use deep learning to display automated emails like newsletters, invoices, and promotions in a separate feed
    fontawesome_icon_name                 : rss

  - title                                 : Smart Screener
    description                           : Take control of your inbox. Pick and choose who you want to recieve emails from
    fontawesome_icon_name                 : thumbs-up
    
  - title                                 : Powerful Tagging System
    description                           : Folders, shmolders. Use tags to quickly organize and find your conversations
    fontawesome_icon_name                 : tag

  - title                                 : Modern Design
    description                           : We've done away with sidebars, nested menus and other archaic e-mail design elements. Welcome to the future of email.
    fontawesome_icon_name                 : palette

  - title                                 : Chat View
    description                           : Emails are conversations, not letters in a mailbox. See the entire conversation at a glance with a chat style view
    fontawesome_icon_name                 : comments
  
  - title                                 : Multiple Inboxes
    description                           : Support for all major email services means you don't have to make yet another email account
    fontawesome_icon_name                 : layer-group

  - title                                 : People View
    description                           : See who you're talking to and quickly view interactions with them with Beacon's People View
    fontawesome_icon_name                 : users

  - title                                 : Powerful Search
    description                           : Spotlight style search lets you quickly find what you're looking for
    fontawesome_icon_name                 : search

  - title                                 : File Browser
    description                           : Why crawl through dozens of emails to find an attachment. Quickly search for and find any attachment.
    fontawesome_icon_name                 : file

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.0
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown